#!/bin/sh
#
# @(#) $Revision: 1.1 $
QTDIR=/usr/local/qt
QMAKESPEC=linux-g++-64
export QTDIR QMAKESPEC
TRAINDEVHOME=/usr/local/qt5_pyqt5_v1
export TRAINDEVHOME
TRAINBUILDTYPE=all
TRAINBUILDBIT=64
export TRAINBUILDTYPE TRAINBUILDBIT
PATH=$TRAINDEVHOME/bin:$TRAINDEVHOME/lib:$QTDIR/bin:$QTDIR/lib:$PATH
export PATH
LD_LIBRARY_PATH=$TRAINDEVHOME/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

